name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Install Solidity Compiler
        run: |
          sudo add-apt-repository ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install solc

      - name: Install abigen
        run: |
          go install github.com/ethereum/go-ethereum/cmd/abigen@latest

      - name: Build Contract
        run: make contract

      - name: Build Go Binary
        run: make build

      - name: Run Unit Tests
        run: make test

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start Services
        run: |
          make docker-up
          sleep 5
          docker-compose ps

      - name: Run Integration Tests
        run: make test-integration

      - name: Docker Logs on Failure
        if: failure()
        run: docker-compose logs

      - name: Cleanup
        if: always()
        run: | 
          make docker-down
          make clean